config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  resources :tasks
  resources :lists
  devise_for :users
  get "lists/index"
  root "lists#index"

  get "/publicas" => "lists#publicas"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :favorite
  has_many :tasks, inverse_of: :list, :dependent => :destroy
  accepts_nested_attributes_for :tasks, :reject_if => proc {|attributes| attributes['text'].blank? }
  scope :status, -> (public) {where public: public}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
    @status = List.status(true)
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    @lista = List.where(id: params[:lisid])
    @abertas = Task.where(list_id: params[:lisid], active: true)
    @fechadas = Task.where(list_id: params[:lisid], active: false)
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
    @abertas = Task.where(list_id: params[:list], active: true)
    @fechadas = Task.where(list_id: params[:list], active: false)
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to lists_url, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:list_id, :user_id, :comment)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    @favs = Favorite.joins(:list).select("favorites.id, lists.name, lists.id as lisid").where(user_id: current_user)
    @listas = List.where(user_id: current_user)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @tasks = Task.where(list_id: params[:id])
    @abertas = Task.where(active: true, list_id: params[:id])
    @fechadas = Task.where(active: false, list_id: params[:id])
  end

  def publicas
    @status = List.status(true)
  end

  # GET /lists/new
  def new
    @list = List.new
    3.times {@list.tasks.build}
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'Lista criada.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'Lista atualizada.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Lista apagada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:user_id, :name, :public, tasks_attributes: [:id, :text, :active, :_destroy])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to lists_url, notice: 'Tarefa criada.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to lists_url, notice: 'Tarefa atualizada.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Tarefa apagada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:list_id, :text, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/favorites/_form.html.erb
<%= form_for(favorite) do |f| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :list_id, :value => params[:list]  %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, :value => params[:id]  %>
  </div>

  <div class="actions">
    <%= f.submit "Adicionar aos favoritos" %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.id %></td>
        <td><%= favorite.user.id %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1><%= params[:name] %></h1>

<table>
	<thead>
		<tr>
			<th>Tarefas</th>
		</tr>
	</thead>
	<tbody>
		<% @abertas.each do |task| %>
	    	<tr>
	        	<td><%= task.text %></td>
	    	</tr>
	  	<% end %>
	  	<% @fechadas.each do |task| %>
	    	<tr>
	        	<td><del><%= task.text %></del></td>
	    	</tr>
	  	<% end %>
	</tbody>
</table>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Voltar',  {:controller => 'lists', :action => 'publicas'} %>

app/views/favorites/show.html.erb
<p>
<% @lista.each do |list| %>
  <h1><%= list.name %></h1>
</p>

<%= link_to 'Apagar', @favorite, method: :delete, data: { confirm: 'Você tem certeza?' } %> 
<br><br>
<table>
	<thead>
		<tr>
			<th> Tarefas </th>
		</tr>
	</thead>
	<tbody>
		<% @abertas.each do |task| %>
	    	<tr>
	        	<td><%= task.text %></td>
	    	</tr>
	  	<% end %>
	  	<% @fechadas.each do |task| %>
	    	<tr>
	        	<td><del><%= task.text %></del></td>
	    	</tr>
	  	<% end %>
  </tbody>	
</table>
<% end %>
<br>
<%= link_to 'Voltar', lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniapp1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="navbar-text pull-right">
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
  

  	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id  %>
  </div>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :pública? %>
    <%= f.check_box :public %>
  </div>

<h2>Tarefas</h2>

  <%= f.fields_for :tasks do |builder| %>
    <div class="field">
      
      <%= builder.text_field :text %>
    </div>
    <div class="field">
      <%= builder.label :aberta? %>
      <%= builder.check_box :active %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Minhas Listas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listas.each do |list| %>
      <tr>
        <td><%= link_to list.name, list %></td>
        <td><%= list.public ? t("Publica") : t("Privada") %></td>
        <td><%= link_to 'Editar', edit_list_path(list) %></td>
        <td><%= link_to 'Apagar', list, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Nova Lista', new_list_path %>
<br><br>
<h1>Favoritas</h1>
<table>
<thead></thead>
<tbody>
<% @favs.each do |fav| %>

      <tr>
        <td><%= link_to fav.name, favorite_path(fav, :lisid=> fav.lisid) %></td>
      </tr>

<% end %> 
</tbody>
</table>
<br><br>

<%= link_to 'Listas Públicas',  {:controller => 'lists', :action => 'publicas'} %>
<br>

app/views/lists/new.html.erb
<h1>Nova Lista</h1>

<%= render 'form', list: @list %>

<%= link_to 'Voltar', lists_path %>

app/views/lists/publicas.html.erb
<h1>Listas Públicas</h1>

<table>
  <tbody>
    <% @status.each do |publica| %>
      <tr>
        <td><%= link_to publica.name, new_favorite_path(publica, :id=>current_user, :list=> publica.id, :name =>publica.name) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Voltar', lists_path %>

app/views/lists/show.html.erb
<p>
  <h1><%= @list.name %></h1>
</p>

  <strong>Status:</strong>
  <%= @list.public ? t("Pública") : t("Privada") %>
  <br><br><%= link_to 'Editar Lista', edit_list_path(@list) %>
  <br><%= link_to 'Apagar', @list, method: :delete, data: { confirm: 'Você tem certeza?' } %>
<br><br>
<table>
	<thead>
		<tr>
			<th> Tarefa </th>
		</tr>
	</thead>
	<tbody>
		<% @abertas.each do |task| %>
	    	<tr>
	        	<td><%= task.text %></td>
	        	<td><%= link_to 'Editar Tarefa', edit_task_path(task, :list=> @list) %></td>
	        	<td><%= link_to 'Apagar', task, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
	    	</tr>
	  	<% end %>
	  	<% @fechadas.each do |task| %>
	    	<tr>
	        	<td><del><%= task.text %></del></td>
	        	<td><%= link_to 'Editar Tarefa', edit_task_path(task) %></td>
	        	<td><%= link_to 'Apagar', task, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
	    	</tr>
	  	<% end %>
  </tbody>	
</table>

<%= link_to 'Nova Tarefa', new_task_path(:list=> @list) %>
<br>
<%= link_to 'Voltar', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.hidden_field :list_id, :value => params[:list]  %>
  </div>

  <div class="field">
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :aberta? %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Voltar', lists_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Text</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.list.name %></td>
        <td><%= task.text %></td>
        <td><%= task.active %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>Nova Tarefa</h1>

<%= render 'form', task: @task %>

<%= link_to 'Voltar', lists_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @task.list %>
</p>

<p>
  <strong>Text:</strong>
  <%= @task.text %>
</p>

<p>
  <strong>Active:</strong>
  <%= @task.active %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>